apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: magentogcps.gcp.web7.io
spec:
  group: gcp.web7.io
  names:
    kind: MagentoGCP
    plural: magentogcps
    singular: magentogcp
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectId:
                  type: string
                location:
                  type: object
                  properties:
                    zone:
                      type: string
                    region:
                      type: string
                nodeCount:
                  type: integer
                nodeType:
                  type: string
                database:
                  type: object
                  properties:
                    password:
                      type: string
                databaseInstance:
                  type: object
                  properties:
                    version:
                      type: string
                    diskSize:
                      type: integer
                    tier:
                      type: string
                magento:
                  type: object
                  properties:
                    creds:
                      type: object
                      properties:
                        username:
                          type: string
                        password:
                          type: string
                        email:
                          type: string
                    hostname:
                      type: string
                    chart:
                      type: object
                      properties:
                        name:
                          type: string
                        version:
                          type: string
                        repository:
                          type: string
                providerConfigSecretRef:
                  type: object
                  properties:
                    secret:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace: 
                          type: string
            status:
              type: object
              properties:
                ingress:
                  type: object
                  properties:
                    ip:
                      type: string
                    id:
                      type: string
                egress:
                  type: object
                  properties:
                    ip:
                      type: string
                    id:
                      type: string
                router:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                cluster:
                  type: object
                  properties:
                    name:
                      type: string
                    creds:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                network:
                  type: object
                  properties:
                    name:
                      type: string
                    id:
                      type: string
                    ingress:
                      type: object
                      properties:
                        ip:
                          type: string
                subnetwork:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                providers:
                  type: object
                  properties:
                    helm:
                      type: object
                      properties:
                        name:
                          type: string
                    kubernetes:
                      type: object
                      properties:
                        name:
                          type: string
                    gcp:
                      type: object
                      properties:
                        name:
                          type: string
                chartRegistry:
                  type: object
                  properties:
                    url:
                      type: string
                secretsManager:
                  type: object
                  properties:
                    secretStoreName:
                      type: string
                deployments:
                  type: object
                  properties:
                    argoCdProject:
                      type: string
                sqlInstance:
                  type: object
                  properties:
                    database:
                      type: object
                      properties:
                        name:
                          type: string
                    name:
                      type: string
                    host:
                      type: string
                    user:
                      type: object
                      properties:
                        name:
                          type: string
                        password:
                          type: string
                ipRange:
                  type: object
                  properties:
                    name:
                      type: string

      served: true
      referenceable: true