name: Configuration package release
on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io

jobs:

  build-and-pack:
    name: Build and pack
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: CR authentication
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ACCESS_TOKEN }}


    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@github.com"


    - name: Prepare metadata
      id: metadata
      run: git diff --name-only HEAD~1 HEAD | awk -F'/' 'NF >= 2 { print $1 "/" $2 }' | uniq > build.txt;

    - name: Set VERSION env
      run: echo VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}

    - name: Install crossplane CLI
      id: crossplane
      run: curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh" | sh

    - name: Build and push crossplane packages
      run: cat build.txt | xargs -I{} bash -c ' dirname $(find {} -name crossplane.yaml)' | xargs -I{} bash -c './crossplane xpkg build -f {} -o {}/$(basename {})  && ./crossplane xpkg push -f {}/$(basename {}) ${REGISTRY}/${{ github.repository }}/$(basename $(dirname {})):${{ env.VERSION }} || true' || true;

